"""Initial schema update (log table and file tracking)

Revision ID: e19a4e21a2b0
Revises: 
Create Date: 2025-10-10 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19a4e21a2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. TẠO BẢNG LOG MỚI
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=512), nullable=False),
    sa.Column('is_admin_action', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_timestamp'), ['timestamp'], unique=False)

    # 2. THÊM CÁC CỘT MỚI VÀO BẢNG FILE
    with op.batch_alter_table('file', schema=None) as batch_op:
        # Nếu database của bạn đã có bảng 'file' nhưng chưa có 2 cột này
        # Lệnh này sẽ thêm chúng mà KHÔNG XÓA DỮ LIỆU
        batch_op.add_column(sa.Column('last_opened_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('last_opened_at', sa.DateTime(), nullable=True))

    # 3. TẠO CÁC BẢNG CÒN LẠI (user, message, app_version) NẾU CHƯA CÓ
    # Vì lệnh này chạy SAU khi server.py đã tự gọi db.create_all() lần đầu, 
    # nó chỉ đảm bảo các bảng còn thiếu được tạo.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('last_opened_at')
        batch_op.drop_column('last_opened_by')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_timestamp'))

    op.drop_table('log')
    # ### end Alembic commands ###
